<?php

namespace sanyisasha\yii2googleanalytics;

class Component extends \yii\base\Component {
    public function init()
    {
        \Yii::error('Its works!');
        parent::init(); // TODO: Change the autogenerated stub
    }
}